services:
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "finance"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"