name: Build and push image

on:
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy
        run: |
          curl -X POST https://api.github.com/repos/${{ secrets.DOCKER_REPO }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_PAT }} \
          --data '{"event_type": "deploy", "client_payload": { "type": "backend" }}'